on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'varfish-org'
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: rust
          package-name: rocksdb-utils-lookup
          token: ${{ secrets.BOT_TOKEN }}

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created == 'true' }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ steps.release.outputs.release_created == 'true' }}
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.release.outputs.release_created == 'true' }}

      - name: Publish crate
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
